sample_rate: 48000
stft:
  n_fft: 2048
  hop_length: 640
  win_length: 2048
token_rate: 12
crop_seconds: 1.5
chunk_seconds: 1.5
hop_seconds: 0.75
batch_size: 8
epochs: 2
lr: 0.0001
device: cuda
num_workers: 4
save_every: 1000
model:
  hidden_dim: 512
  token_dim: 256
  transformer_layers: 8
  heads: 8
  use_rope: true
  use_group_fsq: true
  # Transformer Decoder configuration
  decoder_depth: 6          # Number of transformer decoder layers (4-8 recommended)
  decoder_patch_size: 16    # Patch size (8=more detail/slower, 16=balanced, 32=faster/less detail)
train:
  # Single-stage training: consistency from step 0
  stage: 2
  stage1_steps: 0
  stage2_steps: 10000
  grad_clip: 1.0
  use_amp: true
  fsq_dropout_schedule:
    - [0, 0.50]
    - [5000, 0.65]
    - [10000, 0.75]
  ddp: false
  use_checkpoint: true
  ema:
    enabled: true
    decay: 0.9999
  # STFT 보조 손실 가중 스케줄(초반 N step만 가중 적용)
  # 예: 0~2000 step: 0.1, 그 이후: 0.0
  recon_weight_schedule:
    - [0, 0.1]
    - [2000, 0.0]
data:
  wav_exts: [".wav", ".flac", ".mp3"]
  segment_seconds: 1.5
  stereo: true
output:
  ckpt_dir: runs/ckpts
  log_dir: runs/logs
logging:
  use_wandb: false
  project: lycodec
  run_name: lycodec_48k
teacher:
  primary:
    enabled: true
    type: mert
    model_name: m-a-p/MERT-v1-330M
    sample_rate: 24000
    feature_hz: 75
    align_weight: 0.1
    window_sec: 0.4
  aux:
    enabled: true
    type: hubert
    model_name: ZhenYe234/hubert_base_general_audio
    sample_rate: 16000
    feature_hz: 50
    align_weight: 0.05
    window_sec: 0.4
