sample_rate: 48000
stft:
  n_fft: 2048
  hop_length: 640
  win_length: 2048
crop_seconds: 1.5
chunk_seconds: 1.5
hop_seconds: 0.75
batch_size: 4
epochs: 2000
lr: 0.0001
device: cuda
num_workers: 12
save_every: 1000
model:
  hidden_dim: 512
  token_dim: 256
  transformer_layers: 8
  heads: 8
  use_rope: true
  token_fps: 24
  rvq_codebook_size: 4096
  decoder_depth: 8
  decoder_patch_size: 16
  use_residual_corrector: true
  corrector_alpha: 0.3
  rvq_drop_start: 0.6
  rvq_drop_end: 0.1
  rvq_drop_decay_steps: 100000

train:
  stage: 2
  stage1_steps: 0
  stage2_steps: 100000
  grad_clip: 1.0
  use_amp: true
  gradient_accumulation_steps: 1

  stft_weight_schedule:
    - [0, 0.7]
    - [100000, 0.7]

  infill_weight: 0.3
  residual_weight: 1.0
  alignment_weight: 0.1
  contrast_weight: 1.0
  target_perplexity: 2048
  sigma_min: 0.002
  sigma_max: 80.0
  rho: 7.0

  use_checkpoint: true
  ema:
    enabled: true
    decay: 0.9999

data:
  wav_exts: [".wav", ".flac", ".mp3"]
  segment_seconds: 1.5
  stereo: true
output:
  ckpt_dir: runs/ckpts
  log_dir: runs/logs
logging:
  use_wandb: true
  project: lycodec
  run_name: lycodec_48k
