sample_rate: 48000
stft:
  n_fft: 2048
  hop_length: 640
  win_length: 2048
token_rate: 12
crop_seconds: 1.5
chunk_seconds: 1.5
hop_seconds: 0.75
batch_size: 8
epochs: 2
lr: 0.0001
device: cuda
num_workers: 4
save_every: 1000
model:
  hidden_dim: 512
  token_dim: 256
  transformer_layers: 8
  heads: 8
  use_rope: true
  use_partitioned_fsq: true  # Use semantic-acoustic separation (replaces use_group_fsq)
  semantic_dim: 120          # Semantic dimensions (120 dims = 2160 discrete values for 3min)
  decoder_depth: 6
  decoder_patch_size: 16
train:
  # Single-stage training: consistency from step 0
  stage: 2
  stage1_steps: 0
  stage2_steps: 10000
  grad_clip: 1.0
  use_amp: true
  fsq_dropout_schedule:
    - [0, 0.50]
    - [5000, 0.65]
    - [10000, 0.75]
  ddp: false
  use_checkpoint: true
  ema:
    enabled: true
    decay: 0.9999
  # STFT 보조 손실 가중 스케줄(초반 N step만 가중 적용)
  # 예: 0~2000 step: 0.1, 그 이후: 0.0
  recon_weight_schedule:
    - [0, 0.1]
    - [2000, 0.0]
  use_semantic_acoustic: true  # Enable semantic-acoustic losses
  use_masked_prediction: false # Disable masked prediction (replaced by AR)
data:
  wav_exts: [".wav", ".flac", ".mp3"]
  segment_seconds: 1.5
  stereo: true
output:
  ckpt_dir: runs/ckpts
  log_dir: runs/logs
logging:
  use_wandb: false
  project: lycodec
  run_name: lycodec_48k
